;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        paredit-wrap-round
        sp-backward-delete-char
        sp-forward-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-semi&comma
        cider-eval-defun-at-point
        mouse-delete-other-windows
        mouse-set-region
        mouse-yank-primary
        smex
        sp--self-insert-command
        ))
